## 启动端口
server:
  port: 9000
spring:
  application:
    name: order-center
  ## 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
    ##  Hikari 连接池配置
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池母子
      pool-name: MyHikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  ## Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    ## 最大链接数量
    max-active: 300
    ## 最长等待时间
    max-wait: 10000
    ## 最大阻塞数量
    max-idle: 100
    ## 最小阻塞时间
    min-idle: 0
    ## 连接超时时间（毫秒）
    timeout: 0
## mybatis-plus
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sixeco.order.model
  global-config:
    sql-parser-cache: true
    db-config:
      #主键类型
      id-type: auto
      #字段策略
      field-strategy: not_null
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
# Logger
logging:
  path: ./logs
